#+TITLE: Weewiki Keyword Scraper
* Overview
This document describes an implementation of a weewiki
keyword scraper. This keyword scraper goes through every
wiki page and looks for any word or phrase surrounded by
the =equal signs= character. The output information will
be written to standard output. From there, this text can
be trivially parsed by external programs.
* Tangled Files
This compiles to a single file, called =keyscrape.c=.

#+NAME: keyscrape.c
#+BEGIN_SRC c :tangle keyscrape.c
#include <stdio.h>
<<funcdefs>>
<<funcs>>
#+END_SRC
* Top Level Function
The function =ww_keyscrape= is a public function designed to
work with the main weewiki CLI.

#+NAME: funcdefs
#+BEGIN_SRC c
int ww_keyscrape(int argc, char *argv[]);
#+END_SRC

#+NAME: funcs
#+BEGIN_SRC c
int ww_keyscrape(int argc, char *argv[])
{
    printf("Coming soon.\n");
    return 0;
}
#+END_SRC
* Parsing A Page
A page from weewiki gets loaded up into memory parsed
line-by-line. The page name must be supplied here as well.

Each line is checked for enclosing equal signs
characters. The left equal must not have a space following it,
and the right equal must not have a space preceding it.

If such a pattern is found, the content inside is captured.
This is considered to be a "word", even if there are
multiple words contained in it. The data is then written
to the specified filehandle, presumably =stdout=.
* Iterating through pages
This is a process that gets applied to each page, and works
very similarly to the =export= command.

Before any iteration can begin, a few bits of
initialization. First the database is opened.

All the pages in the =wiki= table are queried, their keys
and values extracted. The keys and values are fed into the
analyzer.
