#+TITLE: WeeWiki Server
* Overview
This document aims to implement a local http server around
weewiki. Instead of statically generating HTML,
pages are dynamically generated.

The single-header =httpserver.h= program by jeremycw will be
http server implementation.
* Top Files
The top level files are contained the the files
=server.c= and =server.h=.
#+NAME: server.h
#+BEGIN_SRC c :tangle server.h
#ifndef WWSERVER_H
#define WWSERVER_H
<<typedefs>>
<<funcdefs>>
#endif
#+END_SRC
#+NAME: server.c
#+BEGIN_SRC c :tangle server.c
#define _BSD_SOURCE /* to silence usleep warning */
#include <stdio.h>
#include <sqlite3.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <zlib.h>
#define HTTPSERVER_IMPL
#include "httpserver.h/httpserver.h"
#include "orgparse.h"
#include "weewiki.h"
#include "server.h"
#include "jan.h"
<<structs>>
<<global_data>>
<<static_funcdefs>>
<<functions>>
#+END_SRC
* Top Level Function (weewiki_server)
The top-level function for this is =weewiki_server=. Since
this is a command line program, it takes in =argc= and
=argv= as arguments.

=weewiki server= will run the server with all the default
values. It will read the default a.db and weewiki.janet
configuration file. This will be the only thing implemented
for now.

Later, the hope is to be able to pass in a weewiki database
and have everything be served via that file (including
an embedded config file).
#+NAME: funcdefs
#+BEGIN_SRC c
int weewiki_server(weewiki_d *ww, int argc, char *argv[]);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
static int running = 1;

static void quit (int sig)
{
    running = 0;
    printf("Signal Interrupt\n");
}

int weewiki_server(weewiki_d *ww, int argc, char *argv[])
{
    wwserver_d wws;
    wws.ww = ww;
    weewiki_init(ww);
    weewiki_set(ww);
    weewiki_parse_set(ww, parse_org);
    weewiki_print_set(ww, printer);
    weewiki_ud_set(ww, NULL);
    weewiki_is_server_set(ww, 1);

    if (argc >= 3) {
        wwserver_init(&wws, atoi(argv[2]));
    } else {
        wwserver_init(&wws, 8080);
    }

    if (argc >= 2) {
        if (argv[1][0] == '-') {
            /* '-' effectively skips this argument */
            /* needed if one wants to set the port only */
            weewiki_open(ww, "a.db");
            wws.use_sqlar = 0;
        } else {
            weewiki_open(ww, argv[1]);
            wws.use_sqlar = 1;
        }
    } else {
        weewiki_open(ww, "a.db");
        wws.use_sqlar = 0;
    }

    if (wws.use_sqlar) {
        weewiki_janet_loadconfig_internal(wws.env, wws.ww);
    } else {
        weewiki_janet_loadconfig(wws.env);

    }

    wwserver_global_set(&wws);

    if (wws.server != NULL) {
        signal(SIGINT, quit);
        http_server_listen_poll(wws.server);
        while (running) {
            http_server_poll(wws.server);
            usleep(80);
        }
    }
    wwserver_clean(&wws);
    weewiki_close(ww);
    weewiki_clean(ww);
    return 1;
}
#+END_SRC
* Main Data
This is stuff that gets instantiated at startup.
For now, this is probably just the database, though
this could change.
** Struct
#+NAME: typedefs
#+BEGIN_SRC c
typedef struct wwserver_d wwserver_d;
#+END_SRC
Database + http server.
#+NAME: structs
#+BEGIN_SRC c
struct wwserver_d {
    struct http_server_s *server;
    weewiki_d *ww;
    JanetTable *env;
    int use_sqlar;
};
#+END_SRC
** global data setters/getters
- State "DONE"       from "WIP"        [2020-01-16 Thu 18:15]
- State "WIP"        from "TODO"       [2020-01-12 Sun 17:29]
#+NAME: global_data
#+BEGIN_SRC c
static wwserver_d *WWS = NULL;
#+END_SRC
#+NAME: static_funcdefs
#+BEGIN_SRC c
static void wwserver_global_set(wwserver_d *p);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
static void wwserver_global_set(wwserver_d *p)
{
    WWS = p;
}
#+END_SRC
#+NAME: static_funcdefs
#+BEGIN_SRC c
static wwserver_d * wwserver_global_get(void);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
static wwserver_d * wwserver_global_get(void)
{
    return WWS;
}
#+END_SRC
** Startup
#+NAME: funcdefs
#+BEGIN_SRC c
int wwserver_init(wwserver_d *wws, int port);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
int wwserver_init(wwserver_d *wws, int port)
{
    wws->server = http_server_init(port, handle_request);
    wws->env = weewiki_janet_setup();
    wws->use_sqlar = 0;
    return 1;
}
#+END_SRC
** Cleanup
Database is closed. May need to figure out how to cleanly
break out of loop.
#+NAME: funcdefs
#+BEGIN_SRC c
void wwserver_clean(wwserver_d *wws);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
void wwserver_clean(wwserver_d *wws)
{
    if (wws->server != NULL) {
        free(wws->server);
    }
    weewiki_janet_cleanup();
    /* weewiki data gets cleaned elsewhere */
}
#+END_SRC
* Handle Request Callback
The http server library has a single callback entry point.

The handle request callback can be divided up into the
following steps:

- URL parsing
- Writing to buffer
- Pushing buffer to HTTP body
#+NAME: static_funcdefs
#+BEGIN_SRC c
static void handle_request(struct http_request_s* request);
#+END_SRC

This is the struct passed to the org parser.
It will go somewhere else eventually, but
it was first conceived here.

#+NAME: structs
#+BEGIN_SRC c
typedef struct {
    orgparse *op;
    orgparse_state *state;
    wws_buffer *buf;
    wwserver_d *wws;
} wws_parser_d;
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
#define RESPONSE "What is my purpose?"
static void handle_request(struct http_request_s* request)
{
    /* TODO: implement */
    wwserver_d *wws;
    struct http_string_s target;
    const char *name;
    int len;
    wws = wwserver_global_get();
    target = http_request_target(request);

    printf("Request: ");
    fwrite(target.buf, 1, target.len, stdout);
    printf("\n");
    fflush(stdout);

    if (wws == NULL) return;

    len = 0;

    if (is_wiki(&target, &name, &len)) {
        wws_buffer buf;
        sqlite3 *db;
        sqlite3_stmt *stmt;
        int rc;

        struct http_response_s* response = http_response_init();
        wws_buffer_alloc(&buf, 2048);

        db = weewiki_db(wws->ww);
        sqlite3_prepare_v2(db,
                        "SELECT value FROM wiki WHERE(key==?1);",
                        -1,
                        &stmt,
                        NULL);
        sqlite3_bind_text(stmt, 1, name, len, NULL);
        rc = sqlite3_step(stmt);

        if (rc != SQLITE_ROW) {
            wws_buffer_write(&buf, "Could not find page: ", 21);
            wws_buffer_write(&buf, name, len);
            http_response_status(response, 404);
            http_response_header(response, "Content-Type", "text/plain");
        } else {
            orgparse *op;
            orgparse_state *state;
            wws_parser_d pd;
            char *namebuf;

            op = calloc(1, orgparse_size());
            state = calloc(1, orgparse_state_size());
            pd.op = op;
            pd.state = state;
            pd.buf = &buf;
            pd.wws = wws;
            wws_orgparse_setup(op);
            http_response_header(response, "Content-Type", "text/html");
            http_response_status(response, 200);
            weewiki_ud_set(wws->ww, &pd);

            /* copy name to null-terminated string */
            namebuf = calloc(1, len + 1);
            strncpy(namebuf, name, len);
            weewiki_pgname_set(wws->ww, namebuf);

            janet_dostring(wws->env,
                        (const unsigned char *)"(html-header)",
                        NULL, NULL);
            orgparse_init_and_run(op,
                                  (const char *)sqlite3_column_text(stmt, 0),
                                  sqlite3_column_bytes(stmt, 0),
                                  &pd,
                                  state);
            orgparse_end(op, &pd, state);
            janet_dostring(wws->env,
                        (const unsigned char *)"(html-footer)",
                        NULL, NULL);

            weewiki_ud_set(wws->ww, NULL);
            free(op);
            free(state);
            free(namebuf);
        }

        http_response_body(response, (const char *)buf.buf, buf.pos);
        http_respond(request, response);
        wws_buffer_free(&buf);
        sqlite3_finalize(stmt);
    } else if (wws_find_and_serve(wws, request, &target)) {
        return;
    } else {
        /* TODO: pass URLs to Janet to be processed */
        /* if that doesn't work, 404 it */
        struct http_response_s* response = http_response_init();
        http_response_status(response, 404);
        http_response_header(response, "Content-Type", "text/plain");
        http_response_body(response, RESPONSE, sizeof(RESPONSE) - 1);
        http_respond(request, response);
    }
}
#+END_SRC
* Wiki URL Parser (is_wiki)
First thing the requester does is parse the URL, this
determines what to do.

Right now, the only thing the server is programmed to do
is parse org pages to HTML and display. Pages start with
the URL =/wiki=. For example, the URL =/wiki/foo= would
display the page =foo=.

The wiki page is parsed with the function =is_wiki=. If
true, the output will return the name + length.

#+NAME: static_funcdefs
#+BEGIN_SRC c
static int is_wiki(struct http_string_s *target,
                   const char **name,
                   int *len);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
static int is_wiki(struct http_string_s *target,
                   const char **name,
                   int *len)
{
    const char *buf;
    int size;
    int pos;
    static const char *s = "index";

    *len = 0;

    /* '/' defaults to index */
    buf = target->buf;
    size = target->len;

    if (size == 1) {
        *name = s;
        *len = 5;
        return 1;
    }

    /* '/wiki' or '/wiki/' defaults to index */
    if (size == 5 || size == 6) {
        if (!strncmp("/wiki", buf, 5)) {
             if (size == 6 && buf[5] != '/') {
                 return 0;
             } else {
                *name = s;
                *len = 5;
                return 1;
             }
        }
    }

    if (size < 7) return 0; /* minimum: /wiki/N */

    pos = 1; /* skip first whack */

    /* for some reason, "wiki/" must be first */
    if (strncmp("wiki/", &buf[pos], 5)) return 0;

    pos += 5;

    *name = &buf[pos];
    *len = size - pos;

    return 1;
}
#+END_SRC

If it matches, the URL parser will extract the wiki page
name and attempt to retrieve it from the database.
* TODO Custom URL Parser in Janet
If WeeWiki doesn't know what to do with a URL, it will
attempt to pass it along to Janet to get processed. URLs
will be handled in a function called =ww-handle-url=. In
this function, the URL can be processed and Janet can use
=print=, =prin=, and =org= to dynamically generate content.
* HTML buffer callbacks
Instead of writing to a file, HTML is written to a buffer.
This buffer is allocated/freed inside the request callback,
and then bound to the org parser data.

New callbacks will be required for the orgparse routine,
which will be defined below.

This is for now just copy-pasted from the weewiki codebase,
with the bits commented out.
#+NAME: funcdefs
#+BEGIN_SRC c
void wws_orgparse_setup(orgparse *op);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
<<orgparse_callbacks>>
void wws_orgparse_setup(orgparse *op)
{
    orgparse_init(op);
    <<orgparse_html_setup>>
}
#+END_SRC
** Header
Since =<h1>= is only reserved for titles, make all
the header sizes one level smaller.
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_header(void *ud,
                        const char *h,
                        size_t sz,
                        int lvl)
{
    wws_parser_d *p;
    char tmp[16];
    int tmp_sz;
    p = ud;
    tmp_sz = sprintf(tmp, "\n<h%d>", lvl + 1);
    wws_buffer_write(p->buf, tmp, tmp_sz);
    wws_buffer_write(p->buf, h, sz);
    tmp_sz = sprintf(tmp, "</h%d>", lvl + 1);
    wws_buffer_write(p->buf, tmp, tmp_sz);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_header(op, html_header);
#+END_SRC
** Text
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_text(void *ud,
                      const char *str,
                      size_t sz)
{
    wws_parser_d *p;
    p = ud;
    wws_buffer_write(p->buf, str, sz);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_text(op, html_text);
#+END_SRC
** Bold
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_bold(void *ud,
                      const char *str,
                      size_t sz)
{
    /* weewiki_export_d *ex; */
    /* FILE *fp; */
    /* ex = ud; */
    /* fp = ex->fp; */
    /* fprintf(fp, "<b>"); */
    /* fwrite(str, 1, sz, fp); */
    /* fprintf(fp, "</b>"); */
    wws_parser_d *p;
    p = ud;
    wws_buffer_write(p->buf, "<b>", 3);
    wws_buffer_write(p->buf, str, sz);
    wws_buffer_write(p->buf, "</b>", 4);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_bold(op, html_bold);
#+END_SRC
** DONE Aux
CLOSED: [2020-01-15 Wed 15:40]
- State "DONE"       from "TODO"       [2020-01-15 Wed 15:40]
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_aux(void *ud,
                     const char *str,
                     size_t sz)
{
    wws_parser_d *p;
    p = ud;
    janet_dobytes(p->wws->env,
                  (const uint8_t *)str, sz,
                  NULL, NULL);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_aux(op, html_aux);
#+END_SRC
** Newline
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_newline(void *ud,
                         const char *str,
                         size_t sz)
{
    wws_parser_d *p;
    p = ud;
    wws_buffer_write(p->buf, "<br>\n", 6);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_newline(op, html_newline);
#+END_SRC
** Code
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_code(void *ud,
                      const char *str,
                      size_t sz)
{
    wws_parser_d *p;
    p = ud;
    wws_buffer_write(p->buf, "<code>", 6);
    wws_buffer_write(p->buf, str, sz);
    wws_buffer_write(p->buf, "</code>", 7);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_code(op, html_code);
#+END_SRC
** DONE Code Block
CLOSED: [2020-01-16 Thu 18:15]
- State "DONE"       from "TODO"       [2020-01-16 Thu 18:15]
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_codeblock(void *ud,
                           const char *str,
                           size_t sz)
{

    wws_parser_d *p;
    size_t n;
    p = ud;
    wws_buffer_write(p->buf, "<pre><code>", 11);
    for (n = 0; n < sz; n++) {
        switch (str[n]) {
            case '<':
                wws_buffer_write(p->buf, "&lt;", 4);
                break;
            case '>':
                wws_buffer_write(p->buf, "&gt;", 4);
                break;
            default:
                wws_buffer_write(p->buf, &str[n], 1);
                break;
        }
    }
    wws_buffer_write(p->buf, "</pre></code>", 13);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_codeblock(op, html_codeblock);
#+END_SRC
** DONE Name
CLOSED: [2020-01-16 Thu 18:15]
- State "DONE"       from "TODO"       [2020-01-16 Thu 18:15]
Ignored for now.
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_name(void *ud,
                           const char *str,
                           size_t sz)
{
    wws_parser_d *p;
    p = ud;
    wws_buffer_write(p->buf, "<div><b><i>&lt;&lt;", 19);
    wws_buffer_write(p->buf, str, sz);
    wws_buffer_write(p->buf, "&gt;&gt;=</i></b></div>", 23);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_name(op, html_name);
#+END_SRC
** Title
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_title(void *ud,
                           const char *str,
                           size_t sz)
{
    wws_parser_d *p;
    p = ud;
    wws_buffer_write(p->buf, "<title>", 7);
    wws_buffer_write(p->buf, str, sz);
    wws_buffer_write(p->buf, "</title>", 8);
    wws_buffer_write(p->buf, "<h1>", 4);
    wws_buffer_write(p->buf, str, sz);
    wws_buffer_write(p->buf, "</h1>", 5);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_title(op, html_title);
#+END_SRC
** Link
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_link(void *ud,
                      const char *link,
                      size_t link_sz,
                      const char *name,
                      size_t name_sz)
{
    wws_parser_d *p;
    p = ud;
    wws_buffer_write(p->buf, "<a href=\"", 9);
    wws_buffer_write(p->buf, link, link_sz);
    wws_buffer_write(p->buf, "\">", 2);
    wws_buffer_write(p->buf, name, name_sz);
    wws_buffer_write(p->buf, "</a>", 4);
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_link(op, html_link);
#+END_SRC
** Paragraph
#+NAME: orgparse_callbacks
#+BEGIN_SRC c
static void html_pgrph(void *ud, int mode)
{
    wws_parser_d *p;
    p = ud;
    if (mode) {
        wws_buffer_write(p->buf, "</p>", 4);
    } else {
        wws_buffer_write(p->buf, "<p>", 3);
    }
}
#+END_SRC
#+NAME: orgparse_html_setup
#+BEGIN_SRC c
orgparse_set_pgrph(op, html_pgrph);
#+END_SRC
* Buffer Management
All content must be written to in-memory location.
This is handled in a very simple way via a buffer type
called =wws_buffer=.

#+NAME: typedefs
#+BEGIN_SRC c
typedef struct wws_buffer wws_buffer;
#+END_SRC

A =wws_buffer= struct contains the buffer itself (an
unsigned char array), the current position of the buffer
(which is therefore the current size), and the
total size.

#+NAME: structs
#+BEGIN_SRC c
struct wws_buffer {
    int pos;
    int size;
    unsigned char *buf;
};
#+END_SRC

The =wws_buffer= is allocated with the function
=wws_buffer_alloc=. Choose a largish size because this
is the maximum HTML size for a page. Re-allocation could
come later, but for this proof-of concept, a fixed
size is simple and good enough.

#+NAME: funcdefs
#+BEGIN_SRC c
void wws_buffer_alloc(wws_buffer *wb, int size);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void wws_buffer_alloc(wws_buffer *wb, int size)
{
    wb->buf = calloc(1, size);
    wb->pos = 0;
    wb->size = size;
}
#+END_SRC

A allocated buffer must be freed with =wws_buffer_free=.

#+NAME: funcdefs
#+BEGIN_SRC c
void wws_buffer_free(wws_buffer *wb);
#+END_SRC

#+NAME: functions
#+BEGIN_SRC c
void wws_buffer_free(wws_buffer *wb)
{
    wb->size = 0;
    wb->pos = 0;
    free(wb->buf);
}
#+END_SRC

Write to the buffer using =wws_buffer_write=.

#+NAME: funcdefs
#+BEGIN_SRC c
void wws_buffer_write(wws_buffer *wb,
                      const char *buf,
                      int size);
#+END_SRC

This copies over a chunk of data to the internal buffer.
If the buffer is full, it just stops adding and breaks
away.

#+NAME: functions
#+BEGIN_SRC c
void wws_buffer_write(wws_buffer *wb,
                      const char *buf,
                      int size)
{
    int i;
    if (wb->pos >= wb->size) {
       wws_buffer_extend(wb, 512);
    }
    for (i = 0; i < size; i++) {
        wb->buf[wb->pos] = buf[i];
        wb->pos++;
        if (wb->pos >= wb->size) {
            wws_buffer_extend(wb, 512);
        }
    }
}
#+END_SRC

Extending a buffer is done via =wws_buffer_extend=. This is
done automatically inside of =wws_buffer_write=.

#+NAME: funcdefs
#+BEGIN_SRC c
void wws_buffer_extend(wws_buffer *wb, int amount);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
void wws_buffer_extend(wws_buffer *wb, int amount)
{
     wb->size += amount;
     wb->buf = realloc(wb->buf, wb->size);
}
#+END_SRC
* Janet Callbacks
** Org Parser Callback for Janet
- State "DONE"       from "DONE"       [2020-01-15 Wed 17:06]
- State "DONE"       from "WIP"        [2020-01-15 Wed 15:40]
Callback to be used by Janet function.
#+NAME: static_funcdefs
#+BEGIN_SRC c
static void parse_org(weewiki_d *w,
                      const char *str,
                      unsigned int sz);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
static void parse_org(weewiki_d *w,
                      const char *str,
                      unsigned int sz)
{
    orgparse_state_flags *f;
    orgparse_state *state;
    wws_parser_d *pd;

    pd = weewiki_ud(w);
    if (pd == NULL) return;
    state = calloc(1, orgparse_state_size());
    orgparse_state_init(state, pd->op, str, sz, pd);
    f = orgparse_state_flags_get(pd->state);
    orgparse_state_flags_set(state, f);
    orgparse_state_run(state);
    free(state);
}
#+END_SRC
** Print Callback for Janet
Anytime Janet calls print, this is what happens.
#+NAME: static_funcdefs
#+BEGIN_SRC c
static void printer(weewiki_d *w,
                    const char *str,
                    unsigned int sz);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
static void printer(weewiki_d *w,
                    const char *str,
                    unsigned int sz)
{
    wws_parser_d *pd;
    pd = weewiki_ud(w);
    if (pd == NULL) return;
    wws_buffer_write(pd->buf, str, sz);
}
#+END_SRC
* Opening Files
The weewiki server is able to serve files like HTML and CSS
in addition parsing org wiki pages. It looks for a file
after checking for a wiki page.

#+NAME: funcdefs
#+BEGIN_SRC c
int wws_find_and_serve(wwserver_d *wws,
                       struct http_request_s *request,
                       struct http_string_s *str);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
<<mime_type_table>>
int wws_find_and_serve(wwserver_d *wws,
                       struct http_request_s *request,
                       struct http_string_s *str)
{
    char *name;
    int rc;
    char *filebuf;
    unsigned int filesize;
    struct http_response_s* response;
    sqlite3 *db;

    filebuf = NULL;
    filesize = 0;
    response = NULL;

    rc = 0;
    /* copy URL to NULL terminated string */
    name = calloc(1, str->len + 1);
    /* skip the first '/' character */

    db = weewiki_db(wws->ww);
    strncpy(name, &str->buf[1], str->len - 1);

    <<does_file_exist>>

    response = http_response_init();

    <<find_mime_type>>
    <<load_file_into_memory>>
    <<serve_the_file>>

    cleanup:

    if (response != NULL) free(response);
    if (filebuf != NULL) free(filebuf);
    free(name);
    return rc;
}
#+END_SRC

The process of loading a file is as follows:

See if the URL points to an existing file. If it does not
exist, return. The process of this will vary based on if
sqlar mode is enabled.

Additional work must be done to check if the file is a
directory or not. If this doesn't happen, then the program
continues as usual and a segfault occurs.

#+NAME: does_file_exist
#+BEGIN_SRC c
if (wws->use_sqlar) {
    if (!sqlar_file_exists(db, name)) {
        rc = 0;
        goto cleanup;
    }
} else {
    if (access(name, F_OK) != -1) {
        /* Check if non-file (like a directory) */
        struct stat path_stat;
        stat(name, &path_stat);
        if (!S_ISREG(path_stat.st_mode)) {
            rc = 0;
            goto cleanup;
        }
    } else {
        rc = 0;
        goto cleanup;
    }
}
#+END_SRC

The file extension of the file is found. This is used to
determine + set the MIME type in the HTTP request.

#+NAME: find_mime_type
#+BEGIN_SRC c
{
    unsigned int sz;
    unsigned int i;
    unsigned int ext_pos;
    sz = 0;
    ext_pos = 0;
    <<get_extension>>
    <<mime_lookup>>
}
#+END_SRC

The file extension is found by starting at the end of the
URL, and working backwards until the first '.' is found. If
no extension is found, the MIME type is skipped I guess?

#+NAME: get_extension
#+BEGIN_SRC c
for (i = str->len; i > 0; --i) {
    sz++;
    if (str->buf[i - 1] == '.') {
        ext_pos = i - 1;
        break;
    }
}

#+END_SRC

The mime type strings are set via a linear table lookup.

#+NAME: mime_type_table
#+BEGIN_SRC c
typedef struct {
    const char *extension;
    const char *mime_type;
} mime_map;

mime_map mime_table [] = {
    {".css", "text/css"},
    {".gif", "image/gif"},
    {".htm", "text/html"},
    {".html", "text/html"},
    {".jpeg", "image/jpeg"},
    {".jpg", "image/jpeg"},
    {".ico", "image/x-icon"},
    {".js", "application/javascript"},
    {".pdf", "application/pdf"},
    {".mp4", "video/mp4"},
    {".png", "image/png"},
    {".svg", "image/svg+xml"},
    {".xml", "text/xml"},
    {NULL, NULL},
};
#+END_SRC

#+NAME: mime_lookup
#+BEGIN_SRC c
i = 0;
while (1) {
    if (mime_table[i].extension == NULL) break;
    if (!strncmp(mime_table[i].extension,
                 &str->buf[ext_pos],
                 sz)) {
        http_response_header(response,
                             "Content-Type",
                             mime_table[i].mime_type);
        break;
    }
    i++;
}
#+END_SRC

The file is loaded into memory. The process of this will
vary based on if sqlar is enabled.

#+NAME: load_file_into_memory
#+BEGIN_SRC c
if (wws->use_sqlar) {
    int sqlite_rc;
    sqlite_rc = sqlar_extract_to_buffer(db,
                                        name,
                                        &filebuf,
                                        &filesize);
    if (sqlite_rc != SQLITE_OK) {
        rc = 0;
        goto cleanup;
    }
} else {
    FILE *fp;

    fp = fopen(name, "r");
    fseek(fp, 0, SEEK_END);
    filesize = ftell(fp);

    fseek(fp, 0, SEEK_SET);

    filebuf = calloc(1, filesize + 1);
    fread(filebuf, 1, filesize, fp);
}
#+END_SRC

After all this is done, the http request is completed.

#+NAME: serve_the_file
#+BEGIN_SRC c
{
    http_response_body(response, filebuf, filesize);
    http_respond(request, response);
    rc = 1;
    response = NULL;
}
#+END_SRC
* SQLar Operations
** Check if file exists
#+BEGIN_SRC sql
SELECT EXISTS(SELECT name FROM sqlar WHERE NAME is ?1);
#+END_SRC
#+NAME: funcdefs
#+BEGIN_SRC c
int sqlar_file_exists(sqlite3 *db, const char *name);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
int sqlar_file_exists(sqlite3 *db, const char *name)
{
    sqlite3_stmt *stmt;
    int rc;

    sqlite3_prepare(db,
                    "SELECT "
                    "EXISTS("
                    "SELECT name FROM sqlar "
                    "WHERE name is ?1"
                    ");",
                    -1,
                    &stmt,
                    NULL);
    sqlite3_bind_text(stmt, 1, name, -1, SQLITE_STATIC);
    sqlite3_step(stmt);
    rc = sqlite3_column_int(stmt, 0);
    sqlite3_finalize(stmt);
    return rc;
}
#+END_SRC
** Extract to buffer
#+NAME: funcdefs
#+BEGIN_SRC c
int sqlar_extract_to_buffer(sqlite3 *db,
                            const char *name,
                            char **out,
                            unsigned int *size);
#+END_SRC
#+NAME: functions
#+BEGIN_SRC c
int sqlar_extract_to_buffer(sqlite3 *db,
                            const char *name,
                            char **out,
                            unsigned int *size)
{
    char *output;
    unsigned long int out_size;
    int rc;
    sqlite3_stmt *stmt;
    int sz;
    const char *data;
    int data_sz;

    rc = sqlite3_exec(db,
                      "CREATE TABLE IF NOT EXISTS sqlar(\n"
                      "  name TEXT PRIMARY KEY,\n"
                      "  mode INT,\n"
                      "  mtime INT,\n"
                      "  sz INT,\n"
                      "  data BLOB\n"
                      ");", 0, 0, 0);


    sqlite3_prepare(db,
                    "SELECT name, mode, mtime, sz, data FROM sqlar"
                    " WHERE name is ?1",
                    -1,
                    &stmt,
                    NULL);

    sqlite3_bind_text(stmt, 1, name, -1, SQLITE_STATIC);

    rc = sqlite3_step(stmt);

    if(rc != SQLITE_ROW) {
        fprintf(stderr,
                "SQLar: could find file %s\n",
                name);
        sqlite3_finalize(stmt);
        sqlite3_close(db);
        return rc;
    }

    sz = sqlite3_column_int(stmt,3);
    data = sqlite3_column_blob(stmt,4);
    data_sz = sqlite3_column_bytes(stmt,4);

    output = calloc(1, sz + 1);
    if(sz != data_sz) {
        out_size = sz;

        rc = uncompress((Bytef*)output,
                        &out_size,
                        (const Bytef*)data,
                        data_sz);
        if(rc != Z_OK) {
            fprintf(stderr,
                    "Error: could not uncompress data\n");
            return SQLITE_ERROR;
        }
    } else {
        memcpy(output, data, sz);
    }

    *size = sz;
    *out = output;
    sqlite3_finalize(stmt);
    return SQLITE_OK;
}
#+END_SRC
